certstream_url: wss://certstream.calidog.io/
keywords:
  - test
  - keyword
  - yourbrand
whitelist:
  - exclude
  - these
threshold: 1
output:
  console: True
  #file: output.log   # Uncomment to enable file logging